# Generated by Django 5.1.4 on 2025-01-03 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePropietario', models.TextField(db_column='nombre_propietario')),
                ('fechaCreacion', models.DateTimeField(db_column='fecha_creacion', default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Listas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
