"""agregar_tabla

Revision ID: f2b11cdf443d
Revises: 
Create Date: 2024-11-30 08:59:27.136490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b11cdf443d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('precio', sa.Float(precision=2), nullable=False),
    sa.Column('serie', sa.Text(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
